INSERT INTO quanhuyen(TenQH,STT) VALUES("Quận Ninh Kiều",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Quận Bình Thủy",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Quận Cái Răng",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Quận Ô Môn",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Quận Thốt Nốt",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Cờ Đỏ",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Phong Điền",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Thới Lai",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Vĩnh Thạnh",65);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Cái Nước",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Đầm Dơi",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Năm Căn",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Ngọc Hiển",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Phú Tân",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Thới Bình",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Trần Văn Thời",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện U Minh",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Thành Phố Cà Mau",69);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Vĩnh Lợi",94);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Hông Dân",94);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Hòa Bình",94);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Phước Long",94);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Thị xã Giá Rai",94);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Huyện Đông Hải",94);
INSERT INTO quanhuyen(TenQH,STT) VALUES("Thành Phố Bạc Liêu",94);
