INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Kinh","Việt");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Tày","Thổ, Ngạn, Phén, Thù Lao, Pa Dí, Tày Khao");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Thái","Tày Đăm, Tày Mười, Tày Thanh, Mán Thanh, Hàng Bông, Tày Mường, Pa Thay, Thổ Đà Bắc");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Hoa","Hán, Triều Châu, Phúc Kiến, Quảng Đông, Hải Nam, Hạ, Xạ Phạng");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Khơ-me","Cur, Cul, Cu, Thổ, Việt gốc Miên, Krôm");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Mường","Mol, Mual, Mọi, Mọi Bi, Ao Tá, Ậu Tá");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Nùng","Xuồng, Giang, Nùng An, Phàn Sinh, Nùng Cháo, Nùng Lòi, Quý Rim, Khèn Lài");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("HMông","Mèo, Hoa, Mèo Xanh, Mèo Đỏ, Mèo Đen, Ná Mẻo, Mán Trắng");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Dao","Mán, Động, Trại, Xá, Dìu, Miên, Kiềm, Miền, Quần Trắng, Dao Đỏ, Quần Chẹt, Lô Giang, Dao Tiền, Thanh Y, Lan Tẻn, Đại Bản, Tiểu Bản, Cóc Ngáng, Cóc Mùn, Sơn Đầu");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Gia-rai","Giơ-rai, Tơ-buăn, Chơ-rai, Hơ-bau, Hđrung, Chor");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Ngái","Xín, Lê, Đản, Khách Gia");       
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Ê-đê","Ra-đê, Đê, Kpạ, A-đham, Krung, Ktul, Đliê Ruê, Blô, Epan, Mđhur, Bih");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Ba na","Giơ-lar. Tơ-lô, Giơ-lâng, Y-lăng, Rơ-ngao, Krem, Roh, ConKđe, A-la Công, Kpăng Công, Bơ-nâm");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Xơ-Đăng","Xơ-teng, Hđang, Tơ-đra, Mơ-nâm, Ha-lăng, Ca-dong, Kmrâng, ConLan, Bri-la, Tang");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Sán Chay","Cao Lan, Sán Chỉ, Mán Cao Lan, Hờn Bạn, Sơn Tử");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Cơ-ho","Xrê, Nốp, Tu-lốp, Cơ-don, Chil, Lat, Lach, Trinh");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Chăm","Chàm, Chiêm Thành, Hroi");       
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Sán Dìu","Sán Dẻo, Trại, Trại Đất, Mán, Quần Cộc");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Hrê","Chăm Rê, Chom, Krẹ Luỹ");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Mnông","Pnông, Nông, Pré, Bu-đâng, ĐiPri, Biat, Gar, Rơ-lam, Chil");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Ra-glai","Ra-clây, Rai, Noang, La-oang");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Xtiêng","Xa-điêng");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Bru-Vân Kiều","Bru, Vân Kiều, Măng Coong, Tri Khùa");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Thổ","Kẹo, Mọn, Cuối, Họ, Đan Lai, Ly Hà, Tày Pọng, Con Kha, Xá Lá Vàng");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Giáy","Nhắng, Dẩng, Pầu Thìn Nu Nà, Cùi Chu, Xa");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Cơ-tu","Ca-tu, Cao, Hạ, Phương, Ca-tang");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Gié Triêng","Đgiéh, Tareb, Giang Rẫy Pin, Triêng, Treng, Ta-riêng, Ve, Veh, La-ve, Ca-tang");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Mạ","Châu Mạ, Mạ Ngăn, Mạ Xóp, Mạ Tô, Mạ Krung");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Khơ-mú","Xá Cẩu, Mứn Xen, Pu Thênh, Tềnh, Tày Hay");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Co","Cor, Col, Cùa, Trầu");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Tà-ôi","Tôi-ôi, Pa-co, Pa-hi, Ba-hi");  
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Chơ-ro","Dơ-ro, Châu-ro");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Kháng","Xá Khao, Xá Súa, Xá Dón, Xá Dẩng, Xá Hốc, Xá Ái, Xá Bung, Quảng Lâm");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Xinh-mun","Puộc, Pụa");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Hà Nhì","U Ni, Xá U Ni");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Chu ru","Chơ-ru, Chu");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Lào    ","Là Bốc, Lào Nọi");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("La Chí","Cù Tê, La Quả");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("La Ha","Xá Khao, Khlá Phlạo");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Phù Lá","Bồ Khô Pạ, Mu Di Pạ Xá, Phó, Phổ, Va Xơ");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("La Hủ","Lao, Pu Đang, Khù Xung, Cò Xung, Khả Quy");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("4Lự    ","Lừ, Nhuồn, Duôn");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Lô Lô","Mun Di");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Chứt","Sách, Máy, Rục, Mã-liêng, A-rem, Tu vang, Pa-leng, Xơ-Lang, Tơ-hung, Chà-củi, Tắc-củi, U-mo, Xá Lá Vàng");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Mảng","Mảng Ư, Xá Lá Vàng");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Pà Thẻn        Pà Hưng, Tống","undefined");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Co Lao",null);
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Cống","Xắm Khống, Mấng Nhé, Xá Xeng");  
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Bố Y","Chủng Chá, Trọng Gia, Tu Di, Tu Din");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Si La","Cù Dề Xừ, Khả pẻ");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Pu Péo","Ka Pèo, Pen Ti Lô Lô");        
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Brâu","Brao");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Ơ Đu","Tày Hạt");
INSERT INTO dantoc(TenDanToc,TenGoiKhac) VALUES("Rơ măm",null);