// <auto-generated />
using System;
using BackEnd.src.infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240827154214_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.core.Entities.Account", b =>
                {
                    b.Property<string>("TaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BiKhoa")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("LyDoKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("SuDung")
                        .HasColumnType("int");

                    b.HasKey("TaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Board", b =>
                {
                    b.Property<int>("ID_Ban")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Ban"));

                    b.Property<int>("ID_DonViBauCu")
                        .HasColumnType("int");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_Ban");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Candidate", b =>
                {
                    b.Property<string>("ID_ucv")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_ucv");

                    b.ToTable("UngCuVien");
                });

            modelBuilder.Entity("BackEnd.core.Entities.CandidateNoticeDetails", b =>
                {
                    b.Property<int>("ID_ThongBao")
                        .HasColumnType("int");

                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("ChiTietThongBaoUngCuVien");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Constituency", b =>
                {
                    b.Property<int>("ID_DonViBauCu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DonViBauCu"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ID_QH")
                        .HasColumnType("int");

                    b.Property<string>("TenDonViBauCu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_DonViBauCu");

                    b.ToTable("DonViBauCu");
                });

            modelBuilder.Entity("BackEnd.core.Entities.District", b =>
                {
                    b.Property<int>("ID_QH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_QH"));

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TenQH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_QH");

                    b.ToTable("QuanHuyen");
                });

            modelBuilder.Entity("BackEnd.core.Entities.EducationLevel", b =>
                {
                    b.Property<int>("ID_TrinhDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_TrinhDo"));

                    b.Property<string>("TenTrinhDoHocVan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_TrinhDo");

                    b.ToTable("TrinhDoHocVan");
                });

            modelBuilder.Entity("BackEnd.core.Entities.EducationLevelDetails", b =>
                {
                    b.Property<int>("ID_TrinhDo")
                        .HasColumnType("int");

                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("ChiTietTrinhDoHocVan");
                });

            modelBuilder.Entity("BackEnd.core.Entities.ElectionDetails", b =>
                {
                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ID_Phieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiDiemBau")
                        .HasColumnType("datetime(6)");

                    b.ToTable("ChiTietBauCu");
                });

            modelBuilder.Entity("BackEnd.core.Entities.ElectionResults", b =>
                {
                    b.Property<int>("ID_ketQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_ketQua"));

                    b.Property<int>("ID_Cap")
                        .HasColumnType("int");

                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SoLuotBinhChon")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiDiemDangKy")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TyLeBinhChon")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayBD")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID_ketQua");

                    b.ToTable("KetQuaBauCu");
                });

            modelBuilder.Entity("BackEnd.core.Entities.ElectionStatus", b =>
                {
                    b.Property<string>("GhiNhan")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_DonViBauCu")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayBD")
                        .HasColumnType("datetime(6)");

                    b.ToTable("TrangThaiBauCu");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Elections", b =>
                {
                    b.Property<DateTime>("ngayBD")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenKyBauCu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ngayKT")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ngayBD");

                    b.ToTable("KyBauCu");
                });

            modelBuilder.Entity("BackEnd.core.Entities.ListOfPositions", b =>
                {
                    b.Property<int>("ID_Cap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Cap"));

                    b.Property<int>("ID_DonViBauCu")
                        .HasColumnType("int");

                    b.Property<string>("TenCapUngCu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_Cap");

                    b.ToTable("DanhMucUngCu");
                });

            modelBuilder.Entity("BackEnd.core.Entities.LoginHistory", b =>
                {
                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime(6)");

                    b.ToTable("LichSuDangNhap");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Notifications", b =>
                {
                    b.Property<int>("ID_ThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_ThongBao"));

                    b.Property<string>("NoiDungThongBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID_ThongBao");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("BackEnd.core.Entities.PermanentAddress", b =>
                {
                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_QH")
                        .HasColumnType("int");

                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("DiaChiThuongTru");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Province", b =>
                {
                    b.Property<int>("STT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("STT"));

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("STT");

                    b.ToTable("TinhThanh");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Roles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("RoleID");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("BackEnd.core.Entities.TemporaryAddress", b =>
                {
                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_QH")
                        .HasColumnType("int");

                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("DiaChiTamTru");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Vote", b =>
                {
                    b.Property<string>("ID_Phieu")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ngayBD")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID_Phieu");

                    b.ToTable("PhieuBau");
                });

            modelBuilder.Entity("BackEnd.core.Entities.VoterNoticeDetails", b =>
                {
                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_ThongBao")
                        .HasColumnType("int");

                    b.ToTable("ChiTietThongBaoCuTri");
                });

            modelBuilder.Entity("BackEnd.core.Entities.Vouter", b =>
                {
                    b.Property<string>("ID_CuTri")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_CuTri");

                    b.ToTable("CuTri");
                });

            modelBuilder.Entity("BackEnd.src.core.Entities.BallotDetails", b =>
                {
                    b.Property<string>("BinhChon")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ID_Khoa")
                        .HasColumnType("int");

                    b.Property<string>("ID_Phieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("ChiTietPhieuBau");
                });

            modelBuilder.Entity("BackEnd.src.core.Entities.Lock", b =>
                {
                    b.Property<int>("ID_Khoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Khoa"));

                    b.Property<string>("KhoaBiMat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KhoaCongKhai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID_Khoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("BackEnd.src.core.Entities.ResponseCandidate", b =>
                {
                    b.Property<string>("ID_ucv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YKien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PhanHoiUngCuVien");
                });

            modelBuilder.Entity("BackEnd.src.core.Entities.ResponseVoter", b =>
                {
                    b.Property<string>("ID_CuTri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YKien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("PhanHoiCuTri");
                });
#pragma warning restore 612, 618
        }
    }
}
